CREATE TABLE Person
(
    id    int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name  varchar(100) NOT NULL,
    age   int,
    email varchar(100)
);

INSERT INTO Person(name, age, email)
VALUES ('Tom', 40, 'tom@gmail.com');
INSERT INTO Person(name, age, email)
VALUES ('Bob', 51, 'bob@gmail.com');
INSERT INTO Person(name, age, email)
VALUES ('Katy', 25, 'katy@gmail.com');

TRUNCATE TABLE Person;

ALTER TABLE Person
    ADD COLUMN created_at  timestamp,
    ADD COLUMN updated_at  timestamp,
    ADD COLUMN created_who varchar;